services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: top-drink-coffee-app
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      - USE_HTTPS=false
    volumes:
      - app-data:/app/data
    restart: unless-stopped
    networks:
      - top-drink-network

  nginx:
    image: nginx:alpine
    container_name: top-drink-coffee-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - top-drink-network

networks:
  top-drink-network:
    driver: bridge

volumes:
  app-data:
    driver: local
